export const flags = {

 'Andorra': require('../assets/h240/ad.png'),
 'United Arab Emirates': require('../assets/h240/ae.png'),
 'UAE': require('../assets/h240/ae.png'),
 'Afghanistan': require('../assets/h240/af.png'),
 'Antigua and Barbuda': require('../assets/h240/ag.png'),
 'Anguilla': require('../assets/h240/ai.png'),
 'Albania': require('../assets/h240/al.png'),
 'Armenia': require('../assets/h240/am.png'),
 'Angola': require('../assets/h240/ao.png'),
 'Antarctica': require('../assets/h240/aq.png'),
 'Argentina': require('../assets/h240/ar.png'),
 'American Samoa': require('../assets/h240/as.png'),
 'Austria': require('../assets/h240/at.png'),
 'Australia': require('../assets/h240/au.png'),
 'Aruba': require('../assets/h240/aw.png'),
 'Åland Islands': require('../assets/h240/ax.png'),
 'Azerbaijan': require('../assets/h240/az.png'),
 'Bosnia and Herzegovina': require('../assets/h240/ba.png'),
 'Barbados': require('../assets/h240/bb.png'),
 'Bangladesh': require('../assets/h240/bd.png'),
 'Belgium': require('../assets/h240/be.png'),
 'Burkina Faso': require('../assets/h240/bf.png'),
 'Bulgaria': require('../assets/h240/bg.png'),
 'Bahrain': require('../assets/h240/bh.png'),
 'Burundi': require('../assets/h240/bi.png'),
 'Benin': require('../assets/h240/bj.png'),
 'Saint Barthélemy': require('../assets/h240/bl.png'),
 'St. Barth': require('../assets/h240/bl.png'),
 'Bermuda': require('../assets/h240/bm.png'),
 'Brunei': require('../assets/h240/bn.png'),
 'Bolivia': require('../assets/h240/bo.png'),
 'Caribbean Netherlands': require('../assets/h240/bq.png'),
 'Brazil': require('../assets/h240/br.png'),
 'Bahamas': require('../assets/h240/bs.png'),
 'Bhutan': require('../assets/h240/bt.png'),
 'Bouvet Island': require('../assets/h240/bv.png'),
 'Botswana': require('../assets/h240/bw.png'),
 'Belarus': require('../assets/h240/by.png'),
 'Belize': require('../assets/h240/bz.png'),
 'Canada': require('../assets/h240/ca.png'),
 'Cocos (Keeling), Islands': require('../assets/h240/cc.png'),
 'DR Congo': require('../assets/h240/cd.png'),
 'DRC': require('../assets/h240/cd.png'),
 'Central African Republic': require('../assets/h240/cf.png'),
 'CAR': require('../assets/h240/cf.png'),
 'Republic of the Congo': require('../assets/h240/cg.png'),
 'Congo': require('../assets/h240/cg.png'),
 'Switzerland': require('../assets/h240/ch.png'),
 'Côte d\'Ivoire (Ivory Coast),': require('../assets/h240/ci.png'),
 'Ivory Coast': require('../assets/h240/ci.png'),
 'Cook Islands': require('../assets/h240/ck.png'),
 'Chile': require('../assets/h240/cl.png'),
 'Cameroon': require('../assets/h240/cm.png'),
 'China': require('../assets/h240/cn.png'),
 'Colombia': require('../assets/h240/co.png'),
 'Costa Rica': require('../assets/h240/cr.png'),
 'Cuba': require('../assets/h240/cu.png'),
 'Cape Verde': require('../assets/h240/cv.png'),
 'Cabo Verde': require('../assets/h240/cv.png'),
 'Curaçao': require('../assets/h240/cw.png'),
 'Christmas Island': require('../assets/h240/cx.png'),
 'Cyprus': require('../assets/h240/cy.png'),
 'Czechia': require('../assets/h240/cz.png'),
'Germany': require('../assets/h240/de.png'),
 'Djibouti': require('../assets/h240/dj.png'),
 'Denmark': require('../assets/h240/dk.png'),
 'Dominica': require('../assets/h240/dm.png'),
 'Dominican Republic': require('../assets/h240/do.png'),
 'Algeria': require('../assets/h240/dz.png'),
 'Ecuador': require('../assets/h240/ec.png'),
 'Estonia': require('../assets/h240/ee.png'),
 'Egypt': require('../assets/h240/eg.png'),
 'Western Sahara': require('../assets/h240/eh.png'),
 'Eritrea': require('../assets/h240/er.png'),
 'Spain': require('../assets/h240/es.png'),
 'Ethiopia': require('../assets/h240/et.png'),
 'Finland': require('../assets/h240/fi.png'),
 'Fiji': require('../assets/h240/fj.png'),
 'Falkland Islands': require('../assets/h240/fk.png'),
 'Micronesia': require('../assets/h240/fm.png'),
 'Faroe Islands': require('../assets/h240/fo.png'),
 'Faeroe Islands': require('../assets/h240/fo.png'),
 'France': require('../assets/h240/fr.png'),
 'Gabon': require('../assets/h240/ga.png'),
 'England': require('../assets/h240/gb-eng.png'),
 'Northern Ireland': require('../assets/h240/gb-nir.png'),
 'Scotland': require('../assets/h240/gb-sct.png'),
 'Wales': require('../assets/h240/gb-wls.png'),
 'United Kingdom': require('../assets/h240/gb.png'),
 'UK': require('../assets/h240/gb.png'),
 'Grenada': require('../assets/h240/gd.png'),
 'Georgia': require('../assets/h240/ge.png'),
 'French Guiana': require('../assets/h240/gf.png'),
 'Guernsey': require('../assets/h240/gg.png'),
 'Ghana': require('../assets/h240/gh.png'),
 'Gibraltar': require('../assets/h240/gi.png'),
 'Greenland': require('../assets/h240/gl.png'),
 'Gambia': require('../assets/h240/gm.png'),
 'Guinea': require('../assets/h240/gn.png'),
 'Guadeloupe': require('../assets/h240/gp.png'),
 'Equatorial Guinea': require('../assets/h240/gq.png'),
 'Greece': require('../assets/h240/gr.png'),
 'South Georgia': require('../assets/h240/gs.png'),
 'Guatemala': require('../assets/h240/gt.png'),
 'Guam': require('../assets/h240/gu.png'),
 'Guinea-Bissau': require('../assets/h240/gw.png'),
 'Guyana': require('../assets/h240/gy.png'),
 'Hong Kong': require('../assets/h240/hk.png'),
 'Heard Island and McDonald Islands': require('../assets/h240/hm.png'),
 'Honduras': require('../assets/h240/hn.png'),
 'Croatia': require('../assets/h240/hr.png'),
 'Haiti': require('../assets/h240/ht.png'),
 'Hungary': require('../assets/h240/hu.png'),
 'Indonesia': require('../assets/h240/id.png'),
 'Ireland': require('../assets/h240/ie.png'),
 'Israel': require('../assets/h240/il.png'),
 'Isle of Man': require('../assets/h240/im.png'),
 'India': require('../assets/h240/in.png'),
 'British Indian Ocean Territory': require('../assets/h240/io.png'),
 'Iraq': require('../assets/h240/iq.png'),
 'Iran': require('../assets/h240/ir.png'),
 'Iceland': require('../assets/h240/is.png'),
 'Italy': require('../assets/h240/it.png'),
 'Jersey': require('../assets/h240/je.png'),
 'Jamaica': require('../assets/h240/jm.png'),
 'Jordan': require('../assets/h240/jo.png'),
 'Japan': require('../assets/h240/jp.png'),
 'Kenya': require('../assets/h240/ke.png'),
 'Kyrgyzstan': require('../assets/h240/kg.png'),
 'Cambodia': require('../assets/h240/kh.png'),
 'Kiribati': require('../assets/h240/ki.png'),
 'Comoros': require('../assets/h240/km.png'),
 'Saint Kitts and Nevis': require('../assets/h240/kn.png'),
 'North Korea': require('../assets/h240/kp.png'),
 'South Korea': require('../assets/h240/kr.png'),
 'S. Korea': require('../assets/h240/kr.png'),
 'Kuwait': require('../assets/h240/kw.png'),
 'Cayman Islands': require('../assets/h240/ky.png'),
 'Kazakhstan': require('../assets/h240/kz.png'),
 'Laos': require('../assets/h240/la.png'),
 'Lebanon': require('../assets/h240/lb.png'),
 'Saint Lucia': require('../assets/h240/lc.png'),
 'Liechtenstein': require('../assets/h240/li.png'),
 'Sri Lanka': require('../assets/h240/lk.png'),
 'Liberia': require('../assets/h240/lr.png'),
 'Lesotho': require('../assets/h240/ls.png'),
 'Lithuania': require('../assets/h240/lt.png'),
 'Luxembourg': require('../assets/h240/lu.png'),
 'Latvia': require('../assets/h240/lv.png'),
 'Libya': require('../assets/h240/ly.png'),
 'Morocco': require('../assets/h240/ma.png'),
 'Monaco': require('../assets/h240/mc.png'),
 'Moldova': require('../assets/h240/md.png'),
 'Montenegro': require('../assets/h240/me.png'),
 'Saint Martin': require('../assets/h240/mf.png'),
 'Madagascar': require('../assets/h240/mg.png'),
 'Marshall Islands': require('../assets/h240/mh.png'),
 'North Macedonia': require('../assets/h240/mk.png'),
 'Mali': require('../assets/h240/ml.png'),
 'Myanmar': require('../assets/h240/mm.png'),
 'Mongolia': require('../assets/h240/mn.png'),
 'Macau': require('../assets/h240/mo.png'),
 'Macao': require('../assets/h240/mo.png'),
 'Northern Mariana Islands': require('../assets/h240/mp.png'),
 'Martinique': require('../assets/h240/mq.png'),
 'Mauritania': require('../assets/h240/mr.png'),
 'Montserrat': require('../assets/h240/ms.png'),
 'Malta': require('../assets/h240/mt.png'),
 'Mauritius': require('../assets/h240/mu.png'),
 'Maldives': require('../assets/h240/mv.png'),
 'Malawi': require('../assets/h240/mw.png'),
 'Mexico': require('../assets/h240/mx.png'),
 'Malaysia': require('../assets/h240/my.png'),
 'Mozambique': require('../assets/h240/mz.png'),
 'Namibia': require('../assets/h240/na.png'),
 'New Caledonia': require('../assets/h240/nc.png'),
 'Niger': require('../assets/h240/ne.png'),
 'Norfolk Island': require('../assets/h240/nf.png'),
 'Nigeria': require('../assets/h240/ng.png'),
 'Nicaragua': require('../assets/h240/ni.png'),
 'Netherlands': require('../assets/h240/nl.png'),
 'Norway': require('../assets/h240/no.png'),
 'Nepal': require('../assets/h240/np.png'),
 'Nauru': require('../assets/h240/nr.png'),
 'Niue': require('../assets/h240/nu.png'),
 'New Zealand': require('../assets/h240/nz.png'),
 'Oman': require('../assets/h240/om.png'),
 'Panama': require('../assets/h240/pa.png'),
 'Peru': require('../assets/h240/pe.png'),
 'French Polynesia': require('../assets/h240/pf.png'),
 'Papua New Guinea': require('../assets/h240/pg.png'),
 'Philippines': require('../assets/h240/ph.png'),
 'Pakistan': require('../assets/h240/pk.png'),
 'Poland': require('../assets/h240/pl.png'),
 'Saint Pierre and Miquelon': require('../assets/h240/pm.png'),
 'Pitcairn Islands': require('../assets/h240/pn.png'),
 'Puerto Rico': require('../assets/h240/pr.png'),
 'Palestine': require('../assets/h240/ps.png'),
 'Portugal': require('../assets/h240/pt.png'),
 'Palau': require('../assets/h240/pw.png'),
 'Paraguay': require('../assets/h240/py.png'),
 'Qatar': require('../assets/h240/qa.png'),
 'Réunion': require('../assets/h240/re.png'),
 'Romania': require('../assets/h240/ro.png'),
 'Serbia': require('../assets/h240/rs.png'),
 'Russia': require('../assets/h240/ru.png'),
 'Rwanda': require('../assets/h240/rw.png'),
 'Saudi Arabia': require('../assets/h240/sa.png'),
 'Solomon Islands': require('../assets/h240/sb.png'),
 'Seychelles': require('../assets/h240/sc.png'),
 'Sudan': require('../assets/h240/sd.png'),
 'Sweden': require('../assets/h240/se.png'),
 'Singapore': require('../assets/h240/sg.png'),
 'Saint Helena, Ascension and Tristan da Cunha': require('../assets/h240/sh.png'),
 'Slovenia': require('../assets/h240/si.png'),
 'Svalbard and Jan Mayen': require('../assets/h240/sj.png'),
 'Slovakia': require('../assets/h240/sk.png'),
 'Sierra Leone': require('../assets/h240/sl.png'),
 'San Marino': require('../assets/h240/sm.png'),
 'Senegal': require('../assets/h240/sn.png'),
 'Somalia': require('../assets/h240/so.png'),
 'Suriname': require('../assets/h240/sr.png'),
 'South Sudan': require('../assets/h240/ss.png'),
 'São Tomé and Príncipe': require('../assets/h240/st.png'),
 'El Salvador': require('../assets/h240/sv.png'),
 'Sint Maarten': require('../assets/h240/sx.png'),
 'Syria': require('../assets/h240/sy.png'),
 'Eswatini (Swaziland)': require('../assets/h240/sz.png'),
 'Eswatini': require('../assets/h240/sz.png'),
 'Turks and Caicos Islands': require('../assets/h240/tc.png'),
 'Chad': require('../assets/h240/td.png'),
 'French Southern and Antarctic Lands': require('../assets/h240/tf.png'),
 'Togo': require('../assets/h240/tg.png'),
 'Thailand': require('../assets/h240/th.png'),
 'Tajikistan': require('../assets/h240/tj.png'),
 'Tokelau': require('../assets/h240/tk.png'),
 'Timor-Leste': require('../assets/h240/tl.png'),
 'Turkmenistan': require('../assets/h240/tm.png'),
 'Tunisia': require('../assets/h240/tn.png'),
 'Tonga': require('../assets/h240/to.png'),
 'Turkey': require('../assets/h240/tr.png'),
 'Trinidad and Tobago': require('../assets/h240/tt.png'),
 'Tuvalu': require('../assets/h240/tv.png'),
 'Taiwan': require('../assets/h240/tw.png'),
 'Tanzania': require('../assets/h240/tz.png'),
 'Ukraine': require('../assets/h240/ua.png'),
 'Uganda': require('../assets/h240/ug.png'),
 'United States Minor Outlying Islands': require('../assets/h240/um.png'),
 'United States': require('../assets/h240/us.png'),
 'USA': require('../assets/h240/us.png'),
 'Uruguay': require('../assets/h240/uy.png'),
 'Uzbekistan': require('../assets/h240/uz.png'),
 'Vatican City (Holy See)': require('../assets/h240/va.png'),
 'Vatican City': require('../assets/h240/va.png'),
 'Saint Vincent and the Grenadines': require('../assets/h240/vc.png'),
 'St. Vincent Grenadines': require('../assets/h240/vc.png'),
 'Venezuela': require('../assets/h240/ve.png'),
 'British Virgin Islands': require('../assets/h240/vg.png'),
 'United States Virgin Islands': require('../assets/h240/vi.png'),
 'U.S. Virgin Islands': require('../assets/h240/vi.png'),
 'Vietnam': require('../assets/h240/vn.png'),
 'Vanuatu': require('../assets/h240/vu.png'),
 'Wallis and Futuna': require('../assets/h240/wf.png'),
 'Samoa': require('../assets/h240/ws.png'),
 'Kosovo': require('../assets/h240/xk.png'),
 'Yemen': require('../assets/h240/ye.png'),
 'Mayotte': require('../assets/h240/yt.png'),
 'South Africa': require('../assets/h240/za.png'),
 'Zambia': require('../assets/h240/zm.png'),
 'Zimbabwe': require('../assets/h240/zw.png'),
 'World': require('../assets/h240/icons8-globe-100.png'),
 'North America': require('../assets/h240/icons8-world-map-continents-100.png'),
 'Europe': require('../assets/h240/icons8-world-map-continents-100.png'),
 'Asia': require('../assets/h240/icons8-world-map-continents-100.png'),
 'South America': require('../assets/h240/icons8-world-map-continents-100.png'),
 'Oceania': require('../assets/h240/icons8-world-map-continents-100.png'),
 'Africa': require('../assets/h240/icons8-world-map-continents-100.png'),

}